default: &default
  adapter: postgresql
  pool: 5
  port: 5432

development:
  <<: *default
  database: exchange_rate_dev
  username: Tom
  password:
  host: localhost

test:
  <<: *default
  database: exchange_rate_test
  username: Tom
  password:
  host: localhost

production:
  adapter: postgresql
  pool: 5
  preconnect: true

staging:
  adapter: postgresql
  pool: 5
  preconnect: true
